### ISSUE TITLE
wrap folder reorganization 

### ISSUE THREAD

**Issue by gftabor** [borglab/gtsam-project-python#14]
The other warp python template uses git submodules to organize itself, instead of just the full wrap folder here.
https://github.com/borglab/wrap-project-python

The tutorial here says its a gitsubtree?
https://github.com/borglab/gtsam-project-python/blob/master/TUTORIAL.md

It seems if you are suggesting to use wrap as a library,  both examples should support wrap being cloned + built separately rather than included in a project using it? 

The documentation for wrap suggests to clone + build  + install the wrap library, and then to come to this repo(for tutorial) which then will clone and build the wrap library again?
https://github.com/borglab/wrap

**Comment by gftabor** [comment]
Ahhh more exploration of the various packages shows that my comments are likely already on the roadmap, here 

https://github.com/borglab/wrap-project-python/pull/3

**Comment by varunagrawal** [comment]
Yeah this process has many moving parts. I am slowly updating all of them. :slightly_smiling_face:

**Comment by gftabor** [comment]
https://github.com/borglab/gtsam-project-python/pull/16
