### ISSUE TITLE
Compilation requires gtsam/utilities.h

### ISSUE THREAD

**Issue by Rooholla-KhorramBakht** [borglab/gtsam-project-python#21]
Thank you for this great support for GTSAM. In compiling the package using GTSAM 4.1.0, I noticed that the package requires the utilities.h file from the "develop" branch of the GTSAM. Simply copying it resolved the issue. It would be nice if this file could be merged into the release branches officially.

**Comment by varunagrawal** [comment]
This has been done with the recent 4.2 release. Closing as a result. :)
